detection_method: opencv

items:
  1:
    label: orange
    name: orange
    gripper_pos: 20
    hsv_config:
      h_max: 47
      h_min: 0
      invert: 0
      s_max: 255
      s_min: 119
      v_max: 210
      v_min: 78
    offsets:
      x: 0.08
      y: 0.0
      z: 0.03
  -1:
    label: plate
    name: plate
    gripper_pos: 100
    hsv_config:
      h_max: 49
      h_min: 13
      invert: 0
      s_max: 102
      s_min: 34
      v_max: 160
      v_min: 82
    offsets:
      x: 0.15
      y: -0.05
      z: 0.05

special_actions:
  0: home
  1: random-pose
