detection_method: yolo

items:
  1:
    name: "mouse"
    label: "mouse"
    offsets: {x: 0.08, y: 0.00, z: 0.03}
    gripper_pos: 10
  -1:
    name: "orange mouse pad"
    label: "orange mouse pad"
    offsets: {x: 0.15, y: -0.05, z: 0.05}
    gripper_pos: 100

special_actions:
  0: "home"
  1: "random-pose"