detection_method: opencv
items:
  -1:
    gripper_pos: 100
    hsv_config:
      h_max: 126
      h_min: 92
      invert: 0
      s_max: 104
      s_min: 73
      v_max: 168
      v_min: 142
    label: plate
    name: plate
    offsets:
      x: 0.15
      y: -0.05
      z: 0.05
    roi:
    - 38
    - 105
    - 494
    - 362
  1:
    gripper_pos: 20
    hsv_config:
      h_max: 47
      h_min: 0
      invert: 0
      s_max: 255
      s_min: 119
      v_max: 210
      v_min: 78
    label: orange
    name: orange
    offsets:
      x: 0.08
      y: 0.0
      z: 0.03
special_actions:
  0: home
  1: random-pose
